# Generated by Django 4.0.3 on 2022-05-17 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(default='', max_length=100)),
                ('answer_2', models.CharField(default='', max_length=100)),
                ('answer_3', models.CharField(default='', max_length=100)),
                ('answer_4', models.CharField(default='', max_length=100)),
                ('answer_5', models.CharField(default='', max_length=100)),
                ('answer_6', models.CharField(default='1,2,3', max_length=100)),
                ('answer_7', models.CharField(default='1,2,3', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
