# Generated by Django 4.0.3 on 2022-05-29 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMoreQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(default='2.5', max_length=100)),
                ('answer_2', models.CharField(default='2.5', max_length=100)),
                ('answer_3', models.CharField(default='2.5', max_length=100)),
                ('answer_4', models.CharField(default='2.5', max_length=100)),
                ('answer_5', models.CharField(default='2.5', max_length=100)),
                ('answer_6', models.CharField(default='2.5', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
