# Generated by Django 4.0.4 on 2022-04-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_userquestions_rename_answer_question_question_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_7',
            field=models.CharField(default='', max_length=100),
        ),
    ]
