# Generated by Django 4.0.3 on 2022-04-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_userquestions_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestions',
            name='question',
        ),
    ]
