# Generated by Django 4.0.3 on 2022-04-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_userquestions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestions',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.question'),
        ),
    ]
