# Generated by Django 4.0.3 on 2022-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_userquestions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestions',
            name='value',
        ),
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
