# Generated by Django 4.0.3 on 2022-04-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='value',
        ),
    ]
