# Generated by Django 4.0.4 on 2022-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_remove_question_question_id_remove_question_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestions',
            name='answer_6',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='answer_7',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='question',
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_6_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_6_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_6_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_7_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_7_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_7_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='count_1',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='count_2',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='count_3',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='count_4',
            field=models.IntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
