# Generated by Django 4.0.4 on 2022-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_remove_userquestions_answer_6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('feature_1', models.IntegerField()),
                ('feature_2', models.IntegerField()),
                ('feature_3', models.IntegerField()),
                ('feature_4', models.IntegerField()),
                ('feature_5', models.IntegerField()),
            ],
        ),
    ]
