# Generated by Django 4.0.4 on 2022-04-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_clothes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='answer_6_1',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='answer_6_2',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='answer_6_3',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='answer_7_1',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='answer_7_2',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='answer_7_3',
        ),
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_6',
            field=models.CharField(default='1,2,3', max_length=100),
        ),
        migrations.AddField(
            model_name='userquestions',
            name='answer_7',
            field=models.CharField(default='1,2,3', max_length=100),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='feature_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='feature_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='feature_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='feature_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='feature_5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userquestions',
            name='count_1',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='userquestions',
            name='count_2',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='userquestions',
            name='count_3',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='userquestions',
            name='count_4',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
