# Generated by Django 4.0.4 on 2022-04-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_remove_clothes_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestions',
            name='count_1',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='count_2',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='count_3',
        ),
        migrations.RemoveField(
            model_name='userquestions',
            name='count_4',
        ),
    ]
