# Generated by Django 4.0.4 on 2022-04-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_remove_userquestions_count_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clothes',
        ),
    ]
