# Generated by Django 4.0.4 on 2022-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shop_phone_num',
        ),
        migrations.AddField(
            model_name='user',
            name='shop_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
