# Generated by Django 4.0.3 on 2022-05-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
