# Generated by Django 4.0.3 on 2022-05-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_off_percent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
