# Generated by Django 4.0.3 on 2022-05-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AddField(
            model_name='user',
            name='shop_address',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_phone_num',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
