# Generated by Django 4.0.3 on 2022-05-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shop_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
