# Generated by Django 4.0.3 on 2022-05-31 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_constantstyles_order_off_cost_order_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='productandstyle',
            name='product_group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productandstyle',
            name='product_image',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='UserMoreStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
