# Generated by Django 4.1.5 on 2023-05-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_integer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
