# Generated by Django 4.0.4 on 2022-04-22 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_description', models.CharField(max_length=1000, null=True)),
                ('style_image_url', models.URLField(null=True)),
                ('style_param_1', models.IntegerField(default=0)),
                ('style_param_2', models.IntegerField(default=0)),
                ('style_param_3', models.IntegerField(default=0)),
                ('style_param_4', models.IntegerField(default=0)),
                ('style_param_5', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
