# Generated by Django 4.0.3 on 2022-05-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product_product_off_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop',
            new_name='shop_id',
        ),
    ]
