# Generated by Django 4.0.4 on 2022-04-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_style_userstyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstyle',
            old_name='style',
            new_name='style_id',
        ),
        migrations.RenameField(
            model_name='userstyle',
            old_name='user',
            new_name='user_id',
        ),
    ]
