# Generated by Django 4.0.4 on 2022-05-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_shop_product_shop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
