# Generated by Django 4.1.4 on 2023-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_product_sold_date',
            field=models.DateField(null=True),
        ),
    ]
