# Generated by Django 4.0.4 on 2022-04-24 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_style_userstyle_style_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=1000)),
                ('shop_description', models.CharField(max_length=5000, null=True)),
                ('shop_address', models.CharField(max_length=2000, null=True)),
                ('shop_phone_num', models.IntegerField(null=True)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=2000, null=True)),
                ('product_brand', models.CharField(max_length=100, null=True)),
                ('product_color', models.CharField(max_length=100)),
                ('product_size', models.CharField(max_length=100)),
                ('product_price', models.BigIntegerField()),
                ('product_off_percent', models.IntegerField(default=0)),
                ('product_image', models.URLField(null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.category')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.shop')),
                ('style_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.style')),
            ],
        ),
    ]
