# Generated by Django 4.1.5 on 2023-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_codesforusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesforusers',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
