# Generated by Django 4.0.4 on 2022-05-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_shop_id_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.product'),
        ),
    ]
