# Generated by Django 4.1.4 on 2023-04-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_product_last_product_sold_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_inventory',
            field=models.IntegerField(default=0),
        ),
    ]
