# Generated by Django 4.0.4 on 2022-04-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_category_shop_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='style_description',
        ),
    ]
