# Generated by Django 4.0.4 on 2022-05-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_style_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_off_percent',
            field=models.IntegerField(default=0),
        ),
    ]
