# Generated by Django 4.0.4 on 2022-05-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_design',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usershoppingcart',
            name='status',
            field=models.CharField(default='not Accepted', max_length=100, null=True),
        ),
    ]
