# Generated by Django 4.0.3 on 2022-05-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_product_country_product_product_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shop_description',
        ),
    ]
