# Generated by Django 4.1.5 on 2023-04-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_score_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='last_product_sold_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
