# Generated by Django 4.0.4 on 2022-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
