# Generated by Django 4.0.4 on 2022-05-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_category_shop_product_alter_usershoppingcart_product'),
        ('shop', '0002_product_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
