# Generated by Django 4.1.4 on 2023-05-04 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.BigIntegerField()),
                ('upload', models.FileField(null=True, upload_to='uploads/')),
                ('inventory', models.IntegerField(default=0)),
                ('initial_inventory', models.IntegerField(default=0)),
                ('product_size', models.CharField(max_length=100, null=True)),
                ('product_group', models.CharField(max_length=100, null=True)),
                ('product_image', models.CharField(max_length=2000, null=True)),
                ('product_color', models.CharField(max_length=100, null=True)),
                ('product_height', models.IntegerField(default=0)),
                ('product_design', models.CharField(max_length=100, null=True)),
                ('product_material', models.CharField(max_length=100, null=True)),
                ('product_country', models.CharField(max_length=100, null=True)),
                ('product_off_percent', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0, null=True)),
                ('number_of_votes', models.IntegerField(default=0, null=True)),
                ('last_product_sold_date', models.DateTimeField(null=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
